<?php
return [
    'default_mode' => env('PAGINATION_DEFAULT_MODE', 'auto'),
    'default_limit' => 50,
    'max_limit' => 200,
    'cursor_threshold' => 50000,
    'max_offset' => 50000,

    'resources' => [
        // Master Data Screens (Offset Mode capped at 50,000)
        'products' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'barcode', 'sku', 'selling_price', 'created_at'],
            'groupable_columns' => [
                'active' => ['column' => 'is_active'],
                'brand' => ['column' => 'brand_id', 'join' => ['table' => 'brands', 'foreign' => 'brand_id', 'local' => 'id'], 'label_from' => 'brands.name'],
            ],
        ],
        'customers' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
        ],
        'suppliers' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
            // is_active isn't groupable here: SupplierController::index() only ever lists
            // active suppliers (hardcoded where('is_active', true)), so grouping by it would
            // always resolve to a single all-true bucket.
            'groupable_columns' => [
                'city_id' => ['column' => 'city'],
            ],
        ],
        'employees' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
            ],
        ],
        'brands' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
            ],
        ],
        'categories' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'created_at'],
        ],
        'taxes' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'rate', 'created_at'],
            'groupable_columns' => [
                'taxType' => ['column' => 'type'],
            ],
        ],
        'agents' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
            ],
        ],
        'transports' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'vehicle_no', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
            ],
        ],
        'sizes' => [
            'mode' => 'offset',
            'default_sort' => 'sort_order',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'sort_order', 'created_at'],
        ],
        'attribute_values' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'value', 'code', 'sort_order', 'created_at'],
        ],
        'users' => [
            'mode' => 'offset',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'username', 'email', 'created_at'],
        ],
        // offset, not cursor: the controller's fixed "unread first, then newest" sort uses
        // orderByRaw('read_at IS NOT NULL'), which cursorPaginate() can't encode into a keyset
        // WHERE clause (it needs real column names, not an arbitrary SQL expression).
        'notifications' => [
            'mode' => 'offset',
            'default_limit' => 20,
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
        ],

        // High-Volume Transactions & Logs (Cursor Keyset UX)
        'pos_sales' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'sale_date', 'invoice_no', 'grand_total', 'created_at'],
        ],
        'pos_old_sales' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'sale_date', 'invoice_no', 'created_at'],
        ],
        'pos_returns' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'return_date', 'return_no', 'total_refund', 'created_at'],
        ],
        'direct_purchases' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'purchase_date', 'purchase_no', 'invoice_no', 'total_amount', 'created_at'],
        ],
        'stock_transactions' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'created_at', 'quantity'],
        ],
        'customer_orders' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'order_date', 'order_no', 'total_amount', 'created_at'],
        ],
        'supplier_payments' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'payment_date', 'voucher_no', 'amount', 'created_at'],
        ],
        'purchase_invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
        ],
        'invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
        ],
        'purchase_returns' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'return_date', 'return_no', 'grand_total', 'created_at'],
        ],
        'inventory_entries' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'entry_date', 'entry_no', 'created_at'],
        ],
        'cash_register_sessions' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'opened_at', 'closed_at', 'status', 'created_at'],
        ],
        'transport_entries' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'lr_no', 'lr_date', 'created_at'],
        ],
        'barcodes' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'barcode', 'batch_no', 'created_at'],
        ],
        'physical_stocks' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'audit_date', 'audit_no', 'created_at'],
        ],
        'sales_approvals' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'approval_date', 'approval_no', 'created_at'],
        ],
        'dealer_invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
        ],
        'settlements' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'settlement_date', 'batch_no', 'created_at'],
        ],
        'stock_outwards' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'outward_date', 'outward_no', 'created_at'],
        ],
        'attendance' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'date', 'created_at'],
        ],
        'audit_logs' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'created_at'],
        ],
    ],
];
