<?php
return [
    'default_mode' => env('PAGINATION_DEFAULT_MODE', 'auto'),
    'default_limit' => 50,
    'max_limit' => 200,
    'cursor_threshold' => 50000,
    'max_offset' => 50000,

    'resources' => [
        // Master Data Screens (Offset Mode capped at 50,000)
        'products' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'barcode', 'sku', 'selling_price', 'created_at'],
            'groupable_columns' => [
                'active' => ['column' => 'is_active'],
                'brand' => ['column' => 'brand_id', 'join' => ['table' => 'brands', 'foreign' => 'brand_id', 'local' => 'id'], 'label_from' => 'brands.name'],
                'productGroup' => ['column' => 'category_id', 'join' => ['table' => 'categories', 'foreign' => 'category_id', 'local' => 'id'], 'label_from' => 'categories.name'],
                'name' => ['column' => 'name'],
                'code' => ['column' => 'code'],
                'hsn' => ['column' => 'hsn_code'],
                'type' => ['column' => 'type'],
                'uom' => ['column' => 'unit'],
                'section' => ['column' => 'section'],
                'sellingMode' => ['column' => 'selling_mode'],
                'barcodeMode' => ['column' => 'barcode_mode'],
                'barcodeSource' => ['column' => 'barcode_source'],
                'discountMode' => ['column' => 'discount_mode'],
                'purchasePlanMode' => ['column' => 'purchase_plan_mode'],
                'expectedGender' => ['column' => 'expected_gender'],
                'dumping' => ['column' => 'dumping'],
                'cess' => ['column' => 'cess'],
                'dailyPrice' => ['column' => 'daily_price'],
                'isCore' => ['column' => 'is_core'],
                'excludeReward' => ['column' => 'exclude_reward'],
                'autoPo' => ['column' => 'auto_po'],
                'createdBy' => ['column' => 'created_by'],
                'updatedBy' => ['column' => 'updated_by'],
            ],
        ],
        'customers' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
            'groupable_columns' => [
                'customerType' => ['column' => 'customer_type'],
                'gender' => ['column' => 'gender'],
                'supplyType' => ['column' => 'supply_type'],
                'city' => ['column' => 'city'],
                'state' => ['column' => 'state'],
                'active' => ['column' => 'is_active'],
            ],
        ],
        'suppliers' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
            // is_active isn't groupable here: SupplierController::index() only ever lists
            // active suppliers (hardcoded where('is_active', true)), so grouping by it would
            // always resolve to a single all-true bucket.
            'groupable_columns' => [
                'city_id' => ['column' => 'city'],
                'state_id' => ['column' => 'state'],
                'name' => ['column' => 'name'],
                'code' => ['column' => 'code'],
            ],
        ],
        'employees' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
                'name' => ['column' => 'name'],
                'department_id' => ['column' => 'department_id'],
            ],
        ],
        'brands' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
                'name' => ['column' => 'name'],
                'code' => ['column' => 'code'],
            ],
        ],
        'categories' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'created_at'],
        ],
        'taxes' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'rate', 'created_at'],
            'groupable_columns' => [
                'taxType' => ['column' => 'type'],
                'name' => ['column' => 'name'],
                'taxCode' => ['column' => 'code'],
            ],
        ],
        'agents' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'email', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
                'name' => ['column' => 'name'],
            ],
        ],
        'transports' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'phone', 'vehicle_no', 'created_at'],
            'groupable_columns' => [
                'is_active' => ['column' => 'is_active'],
                'name' => ['column' => 'name'],
                'contact_person' => ['column' => 'contact_person'],
            ],
        ],
        'sizes' => [
            'mode' => 'offset',
            'default_sort' => 'sort_order',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'code', 'sort_order', 'created_at'],
        ],
        'attribute_values' => [
            'mode' => 'offset',
            'default_sort' => 'name',
            'default_order' => 'asc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'value', 'code', 'sort_order', 'created_at'],
        ],
        'users' => [
            'mode' => 'offset',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'name', 'username', 'email', 'created_at'],
        ],
        // offset, not cursor: the controller's fixed "unread first, then newest" sort uses
        // orderByRaw('read_at IS NOT NULL'), which cursorPaginate() can't encode into a keyset
        // WHERE clause (it needs real column names, not an arbitrary SQL expression).
        'notifications' => [
            'mode' => 'offset',
            'default_limit' => 20,
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
        ],

        // High-Volume Transactions & Logs (Cursor Keyset UX)
        'pos_sales' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'sale_date', 'invoice_no', 'grand_total', 'created_at'],
            'groupable_columns' => [
                'customer_name' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
                'user_name' => ['column' => 'user_id', 'join' => ['table' => 'users', 'foreign' => 'user_id', 'local' => 'id'], 'label_from' => 'users.name'],
            ],
        ],
        'pos_old_sales' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'sale_date', 'invoice_no', 'created_at'],
            // Same underlying pos_sales table as 'pos_sales' above -- same columns available.
            'groupable_columns' => [
                'customer_name' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
                'user_name' => ['column' => 'user_id', 'join' => ['table' => 'users', 'foreign' => 'user_id', 'local' => 'id'], 'label_from' => 'users.name'],
            ],
        ],
        'pos_returns' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'return_date', 'return_no', 'total_refund', 'created_at'],
            'groupable_columns' => [
                'customer_name' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
                // pos_returns has no user_id column -- "User" in the UI is the creator, tracked via created_by.
                'user_name' => ['column' => 'created_by', 'join' => ['table' => 'users', 'foreign' => 'created_by', 'local' => 'id'], 'label_from' => 'users.name'],
            ],
        ],
        'direct_purchases' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'purchase_date', 'purchase_no', 'invoice_no', 'total_amount', 'created_at'],
            // company_name/supplier_name/transport_name are denormalized directly onto this table
            // (unlike most other resources), so no join is needed for these.
            'groupable_columns' => [
                'company' => ['column' => 'company_name'],
                'supplier' => ['column' => 'supplier_name'],
                'status' => ['column' => 'status'],
                'transport' => ['column' => 'transport_name'],
            ],
        ],
        'stock_transactions' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'created_at', 'quantity'],
        ],
        'customer_orders' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'order_date', 'order_no', 'total_amount', 'created_at'],
            'groupable_columns' => [
                'status' => ['column' => 'status'],
                'customerName' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
                'supplier' => ['column' => 'supplier_id', 'join' => ['table' => 'suppliers', 'foreign' => 'supplier_id', 'local' => 'id'], 'label_from' => 'suppliers.name'],
            ],
        ],
        'supplier_payments' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'payment_date', 'voucher_no', 'amount', 'created_at'],
        ],
        'purchase_invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
            'groupable_columns' => [
                'supplier' => ['column' => 'supplier_id', 'join' => ['table' => 'suppliers', 'foreign' => 'supplier_id', 'local' => 'id'], 'label_from' => 'suppliers.name'],
            ],
        ],
        'invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
        ],
        'purchase_returns' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'return_date', 'return_no', 'grand_total', 'created_at'],
            'groupable_columns' => [
                'supplier' => ['column' => 'supplier_id', 'join' => ['table' => 'suppliers', 'foreign' => 'supplier_id', 'local' => 'id'], 'label_from' => 'suppliers.name'],
            ],
        ],
        'inventory_entries' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'entry_date', 'entry_no', 'created_at'],
        ],
        'cash_register_sessions' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'opened_at', 'closed_at', 'status', 'created_at'],
        ],
        'transport_entries' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'lr_no', 'lr_date', 'created_at'],
            'groupable_columns' => [
                'transport' => ['column' => 'transport_id', 'join' => ['table' => 'transports', 'foreign' => 'transport_id', 'local' => 'id'], 'label_from' => 'transports.name'],
            ],
        ],
        'barcodes' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'barcode', 'batch_no', 'created_at'],
        ],
        'physical_stocks' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'audit_date', 'audit_no', 'created_at'],
        ],
        'sales_approvals' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'approval_date', 'approval_no', 'created_at'],
            'groupable_columns' => [
                'status' => ['column' => 'status'],
                'customer_name' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
            ],
        ],
        'dealer_invoices' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'invoice_date', 'invoice_no', 'created_at'],
            'groupable_columns' => [
                'customer_name' => ['column' => 'customer_id', 'join' => ['table' => 'customers', 'foreign' => 'customer_id', 'local' => 'id'], 'label_from' => 'customers.name'],
            ],
        ],
        'settlements' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'settlement_date', 'batch_no', 'created_at'],
        ],
        'stock_outwards' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'outward_date', 'outward_no', 'created_at'],
        ],
        'attendance' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'date', 'created_at'],
        ],
        'audit_logs' => [
            'mode' => 'cursor',
            'default_sort' => 'id',
            'default_order' => 'desc',
            'tie_breaker' => 'id',
            'allowed_sorts' => ['id', 'created_at'],
        ],
    ],
];
